ci: Add arm64 runner to ci
canonical/charm-local-users pull request #19
Opened 2024-07-02 08:42 UTC by jneo8

2024-07-03 01:09 UTC, aieri approved these changes
lgtm aside from failing functional tests

2024-07-03 08:27 UTC, jneo8 commented
The CI failed because functional test try to deploy amd64 ubuntu charm, but we don't have this settings on the repo. Need to check details in zaza.

2024-07-03 09:40 UTC, rgildein requested changes
You are missing overlay for arch=arm64. The libjuju is using default value for architecture if it was not specified, as you can see [here](https://github.com/juju/python-libjuju/blob/b56963442a6deffe46ce1fb5cb41970344263649/juju/model.py#L1949C16-L1949C36).

2024-07-03 10:04 UTC, jneo8 commented on Makefile
> +	sudo apt -y install unzip
We can, but this is not the major task we want to handle here.

2024-07-03 13:46 UTC, gabrielcocenza reviewed
> The CI failed because functional test try to deploy amd64 ubuntu charm, but we don't have this settings on the repo. Need to check details in zaza why it's using amd64 as default.

For zaza you need to pass the env var MODEL_CONSTRAINTS and pass “arch=arm64”. Take a look at this example that I did during the [sprint](https://github.com/canonical/charmed-openstack-upgrader/pull/408/files)

2024-07-04 02:03 UTC, chanchiwai-ray requested changes

2024-07-04 02:03 UTC, chanchiwai-ray commented on Makefile
> +	sudo apt -y install unzip
Why was this added? I don't see it was used anywhere in the PR. Even if we do use it somewhere, it's not ideal to put a `sudo xxx` in the `Makefile` as developer will use this in their local machine, and some could have a password-less `sudo`

2024-07-08 08:13 UTC, rgildein commented on Makefile
> +	sudo apt -y install unzip
There is unzip used later in Makefile. I'll suggest dropping that one also.

2024-07-08 08:17 UTC, rgildein commented
> MODEL_CONSTRAINTS

The constraints could be set by [`model-constraints`](https://juju.is/docs/juju/juju-model-constraints) and zaza can configure it for us. Nice, I did not know about it :+1:

2024-07-11 05:12 UTC, rgildein commented on Makefile
> +	sudo apt -y install unzip
> We can, but this is not the major task we want to handle here.

So why you are adding it here, if it's not part of task.

2024-07-11 08:39 UTC, closed without merging